# Dockerfile for products-ui (Development)

# Use an official Node.js runtime as a parent image
FROM node:20

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to leverage Docker cache
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Make port 5173 available to the world outside this container
# Vite's default port
EXPOSE 5173

# Run the app when the container launches
# The "--host" flag is crucial to expose the server outside the container
CMD ["npm", "run", "dev", "--", "--host"]
